import { SOCIAL_HANDLE } from '@/lib/contact'
import { getSiteUrl } from '@/lib/site'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Anton, IBM_Plex_Sans } from 'next/font/google'
import SiteNav from '@/components/SiteNav'
import Footer from '@/components/Footer'
import { AudioPlayerProvider } from "@/lib/audio/AudioPlayerContext";
import GlobalAudioPlayer from "@/components/audio/GlobalAudioPlayer";
import ViewTransition from '@/components/ViewTransition';
import { Analytics } from '@vercel/analytics/react';


const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
// Anton carries the display type. Space Grotesk was only ever used by the old
// home-page CSS, so swapping it keeps the loaded-font count flat.
const anton = Anton({ weight: ['400'], subsets: ['latin'], variable: '--font-anton' })
const ibmPlex = IBM_Plex_Sans({ 
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-ibm-plex'
})

const SITE_URL = getSiteUrl()
const DESCRIPTION =
  'All-sports perspectives, technology, and the culture around the game. Read The Daily Dribble and listen to Late Night Lake Show.'

/**
 * Site metadata. This used to live in app/head.tsx, which is a Next 13.0/13.1
 * convention that was removed in 13.2. On Next 15 that file was inert, so the
 * site shipped with no Open Graph or Twitter tags at all and every shared link
 * rendered as a bare URL. The card art it pointed at
 * (/uploads/articles/dribbles_og_2024.png) does not exist either, so the card
 * is now generated by app/opengraph-image.tsx instead.
 *
 * `metadataBase` is required for relative image URLs to resolve.
 * The title template lets each page declare just its section name.
 */
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: 'The Daily Dribble',
    template: '%s | The Daily Dribble',
  },
  description: DESCRIPTION,
  openGraph: {
    type: 'website',
    siteName: 'The Daily Dribble',
    title: 'The Daily Dribble',
    description: DESCRIPTION,
    url: SITE_URL,
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    site: `@${SOCIAL_HANDLE}`,
    title: 'The Daily Dribble',
    description: DESCRIPTION,
  },
  alternates: { canonical: '/' },
  robots: { index: true, follow: true },
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta name="view-transition" content="same-origin" />
        <link rel="icon" type="image/png" href="/uploads/articles/dribbles_favicon_1.png" />
      </head>
      <body className={`${inter.variable} ${anton.variable} ${ibmPlex.variable} font-sans min-h-screen flex flex-col`}>
        <ViewTransition />
        <AudioPlayerProvider>
          <SiteNav />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
          <GlobalAudioPlayer />
        </AudioPlayerProvider>
        <Analytics />
      </body>
    </html>
  )
}
